export const CodeProjects = [
  {
    id: 8,
    title: 'Decentraland DAO',
    year: '2022-present',
    description: 'Senior full stack developer.',
    tech: 'Building the governance dApp.',
    url: 'https://governance.decentraland.org',
  },
  {
    id: 7,
    title: 'Underscope',
    year: '2018-2022',
    description: 'Software engineer.',
    tech: 'Web and mobile development.',
    url: 'https://underscope.io',
  },
  {
    id: 6,
    title: 'Spot',
    year: '2021',
    description: 'Development of website for Barcelona-based location agency.',
    url: 'https://spotlocations.com',
  },
  {
    id: 5,
    title: 'Keepy (iot2tangle)',
    year: '2020',
    url: 'https://github.com/iot2tangle/Keepy',
  },
  {
    id: 4,
    title: 'DJMAG Latam',
    year: '2020',
    description: 'Design and development.',
    url: 'https://djmagla.com',
  },
  {
    id: 3,
    title: 'Lo que no pudimos compartir',
    year: '2020',
    description: 'Interactive art project development.',
    url: 'https://www.behance.net/gallery/103563219/Lo-que-no-pudimos-compartir',
  },
  {
    id: 2,
    title: 'XDK2MAM Dashboard',
    year: '2019',
    description: 'Design and development of open source visualization tool for the XDK110 sensor.',
    url: 'https://github.com/xdk2mam/xdk2mam-dashboard',
  },
  {
    id: 1,
    title: 'Dalinha',
    year: '2016',
    description: 'Development for visual artist website.',
    url: 'https://dalinha.com',
  },
]
